apiVersion: v1
kind: Service
metadata:
  labels: {{- include "openmaru-apm.labels" . | nindent 4}}
    project: {{ .Release.Namespace }}
    app: influxdb
  name: influxdb
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: influxdb
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb
  type: ClusterIP