apiVersion: v1
kind: Service
metadata:
  labels: {{- include "openmaru-apm.labels" . | nindent 4}}
    app: mongodb
    project: {{ .Release.Namespace }}
  name: mongodb
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  sessionAffinity: None
  type: ClusterIP