apiVersion: v1
kind: Service
metadata:
  labels: {{- include "openmaru-apm.labels" . | nindent 4}}
    app: openmaru-apm
    project: {{ .Release.Namespace }}
  name: ping
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: openmaru-apm
    port: 5701
    protocol: TCP
    targetPort: 5701
  selector:
    app: openmaru-apm
  sessionAffinity: None
  type: ClusterIP