apiVersion: v1
kind: Service
metadata:
  labels: {{- include "openmaru-apm.labels" . | nindent 4}}
    app: redis
    project: {{ .Release.Namespace }}
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP